/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c4c6cd",
        "on-primary-fixed": "#0b1d2e",
        "tertiary": "#000000",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#e1e3e4",
        "on-background": "#191c1d",
        "tertiary-fixed-dim": "#c4c7c8",
        "error-container": "#ffdad6",
        "primary-fixed": "#d3e4fc",
        "on-primary-container": "#74859b",
        "inverse-primary": "#b7c8df",
        "secondary-container": "#fc7728",
        "surface-variant": "#e1e3e4",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#818485",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#444748",
        "tertiary-container": "#191c1d",
        "surface-dim": "#d9dadb",
        "surface-container": "#edeeef",
        "surface-tint": "#4f6074",
        "secondary-fixed-dim": "#ffb692",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#ffdbcb",
        "on-secondary-container": "#5d2300",
        "outline": "#74777d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#341100",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed-variant": "#7a3000",
        "primary-fixed-dim": "#b7c8df",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#191c1d",
        "on-primary-fixed-variant": "#38485b",
        "on-surface-variant": "#44474c",
        "primary-container": "#0b1d2e",
        "surface-container-highest": "#e1e3e4",
        "surface": "#f8f9fa",
        "secondary": "#9f4200",
        "primary": "#000000",
        "background": "#f8f9fa"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "md": "24px",
        "xs": "4px",
        "container-max": "1280px",
        "gutter": "24px",
        "base": "8px",
        "xl": "80px",
        "lg": "48px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
    }
  },
  plugins: [],
}