/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Paleta cálida AutoTire - naranja quemado / neumático
        primary: "#E65C19",
        "on-primary": "#FFFFFF",
        "primary-container": "#FFDBC6",
        "on-primary-container": "#3A1500",
        "primary-fixed": "#FFDBC6",
        "primary-fixed-dim": "#FFB692",
        secondary: "#1C1C1C",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E65C19",
        "on-secondary-container": "#FFFFFF",
        tertiary: "#6B5E3F",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#F3E2C0",
        "on-tertiary-container": "#241B05",
        error: "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
        background: "#FFF8F0",
        "on-background": "#1C1C1C",
        surface: "#FFFFFF",
        "on-surface": "#1C1C1C",
        "surface-variant": "#F0EDE8",
        "on-surface-variant": "#4F4B44",
        "surface-dim": "#DDD8D1",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FFF8F0",
        "surface-container": "#F5F0E9",
        "surface-container-high": "#EFEAE3",
        "surface-container-highest": "#E9E4DD",
        outline: "#7F7971",
        "outline-variant": "#C9C5BC",
        "inverse-surface": "#31312E",
        "inverse-on-surface": "#F4F0E9",
        "inverse-primary": "#FFB692",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Outfit", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        warm: "0 4px 20px rgba(230, 92, 25, 0.15)",
        "warm-lg": "0 8px 40px rgba(230, 92, 25, 0.2)",
        card: "0 2px 12px rgba(0, 0, 0, 0.06)",
        "card-hover": "0 8px 30px rgba(0, 0, 0, 0.1)",
      },
      animation: {
        "fade-in": "fadeIn 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-up": "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "scale-in": "scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
      },
    },
  },
  plugins: [],
}
